In [13]:
import cv2

In [14]:
import numpy as np
img = np.random.randint(0, 10, (7, 7))
print(img)

[[5 8 6 6 0 7 4]
 [4 2 4 3 7 2 6]
 [1 9 5 5 4 8 5]
 [4 2 0 0 0 1 4]
 [7 0 3 0 1 6 3]
 [2 4 2 3 3 2 7]
 [5 9 0 5 1 7 2]]


In [15]:
img_np = np.ones([7, 7])
print(img_np)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [16]:
kernel = np.array([-1, 0, 1])
img_cv = cv2.resize(img_np, (7, 7))
print(img_cv)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [17]:
kernel = cv2.resize(kernel, (1, 3))
conv_test = cv2.filter2D(img_cv, -1, kernel)
print(conv_test)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [18]:
img_cv[0][0] = 0
img_cv[3][3] = 2
img_cv[6][6] = 3
conv_test = cv2.filter2D(img_cv, -1, kernel)
print(conv_test)

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  2.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [20]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPool2D, Flatten, Dense

In [22]:
classifier = Sequential()
classifier.add(
    Conv2D(32, (3, 3), input_shape = (64, 64, 3), activation = 'relu')
)
classifier.add(MaxPool2D(pool_size = (2, 2)))
classifier.add(Flatten())
classifier.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 62, 62, 32)        896       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 31, 31, 32)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 30752)             0         
Total params: 896
Trainable params: 896
Non-trainable params: 0
_________________________________________________________________


In [23]:
classifier.add(
    Dense(128, activation = 'relu')
)
classifier.add(
    Dense(128, activation = 'relu')
)
classifier.add(
    Dense(128, activation = 'relu')
)
classifier.add(
    Dense(128, activation = 'relu')
)
classifier.add(
    Dense(64, activation = 'relu')
)
classifier.add(
    Dense(32, activation = 'relu')
)
classifier.add(
    Dense(16, activation = 'relu')
)
classifier.add(
    Dense(1, activation = 'sigmoid')
)

classifier.compile(optimizer = 'adam',loss = 'binary_crossentropy',metrics = ['accuracy'])

In [24]:
from keras.preprocessing.image import ImageDataGenerator
train_gen = ImageDataGenerator(rescale = 1. / 255,shear_range = 0.2,zoom_range = 0.2,horizontal_flip = True)
test_gen = ImageDataGenerator(rescale = 1.0 / 255)

In [25]:
trainSet = train_gen.flow_from_directory('Applied-Deep-Learning-with-Keras/Lesson07/Datasets/dataset/training_set',target_size = (64, 64),batch_size = 32,class_mode = 'binary')
testSet = test_gen.flow_from_directory('Applied-Deep-Learning-with-Keras/Lesson07/Datasets/dataset/test_set',target_size = (64, 64),batch_size = 32,class_mode = 'binary')
batch_size = 100
classifier.fit_generator(trainSet,steps_per_epoch = int(10000/batch_size),epochs = 100,validation_data = testSet,validation_steps = int(2500/batch_size))

Found 20000 images belonging to 2 classes.
Found 5000 images belonging to 2 classes.
Instructions for updating:
Please use Model.fit, which supports generators.
Epoch 1/100
100/100 [==============================] - 76s 756ms/step - loss: 0.6928 - accuracy: 0.5331 - val_loss: 0.6962 - val_accuracy: 0.4688
Epoch 2/100
100/100 [==============================] - 86s 858ms/step - loss: 0.6606 - accuracy: 0.5981 - val_loss: 0.6229 - val_accuracy: 0.6363
Epoch 3/100
100/100 [==============================] - 62s 620ms/step - loss: 0.6281 - accuracy: 0.6562 - val_loss: 0.6077 - val_accuracy: 0.6913
Epoch 4/100
100/100 [==============================] - 57s 568ms/step - loss: 0.6124 - accuracy: 0.6666 - val_loss: 0.5844 - val_accuracy: 0.7013
Epoch 5/100
100/100 [==============================] - 41s 413ms/step - loss: 0.5761 - accuracy: 0.6981 - val_loss: 0.6045 - val_accuracy: 0.6775
Epoch 6/100
100/100 [==============================] - 42s 425ms/step - loss: 0.5738 - accuracy: 0.7053 - val

D:\anaconda\lib\site-packages\PIL\TiffImagePlugin.py:763: UserWarning: Possibly corrupt EXIF data.  Expecting to read 32 bytes but only got 0. Skipping tag 270
  warnings.warn(
D:\anaconda\lib\site-packages\PIL\TiffImagePlugin.py:763: UserWarning: Possibly corrupt EXIF data.  Expecting to read 5 bytes but only got 0. Skipping tag 271
  warnings.warn(
D:\anaconda\lib\site-packages\PIL\TiffImagePlugin.py:763: UserWarning: Possibly corrupt EXIF data.  Expecting to read 8 bytes but only got 0. Skipping tag 272
  warnings.warn(
D:\anaconda\lib\site-packages\PIL\TiffImagePlugin.py:763: UserWarning: Possibly corrupt EXIF data.  Expecting to read 8 bytes but only got 0. Skipping tag 282
  warnings.warn(
D:\anaconda\lib\site-packages\PIL\TiffImagePlugin.py:763: UserWarning: Possibly corrupt EXIF data.  Expecting to read 8 bytes but only got 0. Skipping tag 283
  warnings.warn(
D:\anaconda\lib\site-packages\PIL\TiffImagePlugin.py:763: UserWarning: Possibly corrupt EXIF data.  Expecting to read 2

100/100 [==============================] - 23s 225ms/step - loss: 0.5309 - accuracy: 0.7312 - val_loss: 0.5656 - val_accuracy: 0.7063
Epoch 13/100
100/100 [==============================] - 20s 197ms/step - loss: 0.5231 - accuracy: 0.7387 - val_loss: 0.5255 - val_accuracy: 0.7262
Epoch 14/100
100/100 [==============================] - 18s 181ms/step - loss: 0.5246 - accuracy: 0.7403 - val_loss: 0.5275 - val_accuracy: 0.7500
Epoch 15/100
100/100 [==============================] - 19s 185ms/step - loss: 0.5344 - accuracy: 0.7366 - val_loss: 0.5057 - val_accuracy: 0.7588
Epoch 16/100
100/100 [==============================] - 20s 199ms/step - loss: 0.5309 - accuracy: 0.7369 - val_loss: 0.5345 - val_accuracy: 0.7450
Epoch 17/100
100/100 [==============================] - 17s 165ms/step - loss: 0.5113 - accuracy: 0.7513 - val_loss: 0.5177 - val_accuracy: 0.7350
Epoch 18/100
100/100 [==============================] - 15s 154ms/step - loss: 0.4947 - accuracy: 0.7469 - val_loss: 0.5094 - val_a

100/100 [==============================] - 12s 123ms/step - loss: 0.3975 - accuracy: 0.8191 - val_loss: 0.4931 - val_accuracy: 0.7700
Epoch 68/100
100/100 [==============================] - 13s 126ms/step - loss: 0.3927 - accuracy: 0.8238 - val_loss: 0.4981 - val_accuracy: 0.7837
Epoch 69/100
100/100 [==============================] - 12s 123ms/step - loss: 0.3980 - accuracy: 0.8234 - val_loss: 0.6024 - val_accuracy: 0.7575
Epoch 70/100
100/100 [==============================] - 13s 126ms/step - loss: 0.3809 - accuracy: 0.8250 - val_loss: 0.5418 - val_accuracy: 0.7575
Epoch 71/100
100/100 [==============================] - 13s 125ms/step - loss: 0.3951 - accuracy: 0.8159 - val_loss: 0.5104 - val_accuracy: 0.7688
Epoch 72/100
100/100 [==============================] - 13s 129ms/step - loss: 0.3729 - accuracy: 0.8397 - val_loss: 0.6388 - val_accuracy: 0.7350
Epoch 73/100
100/100 [==============================] - 12s 123ms/step - loss: 0.3846 - accuracy: 0.8347 - val_loss: 0.4902 - val_a

In [26]:
from tensorflow.keras.preprocessing import image
new_image = image.load_img('test_image_2.jpg',target_size = (64, 64))
new_image = image.img_to_array(new_image)
new_image = np.expand_dims(new_image, axis = 0)
result = classifier.predict(new_image)
if result[0][0] == 1:
    prediction = 'Dog'
else:
    prediction = 'Cat' 
print(prediction)

Cat
