In [1]:
import numpy as np
v1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(v1)

[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
m1 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9],[10,11,12]])
print(m1)
print(m1.shape)
m2 = np.matrix([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

print(m2)
print(m2.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [5]:
t1 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(t1)
print(t1.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [8]:
m3 = m1 + m2
print(m3)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [20 22 24]]


In [10]:
m3 = np.array([[1,2,3],[4,5,6],[7,8,9],])
print(m3.shape)
m4 = np.array([[4,5,6],[7,8,9],[10,11,12]])
print(m4.shape)

(3, 3)
(3, 3)


In [11]:
m5 = m3 * m4
print(m5)

[[  4  10  18]
 [ 28  40  54]
 [ 70  88 108]]


In [12]:
print(m1.T)
print(m1)

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [13]:
m5 = m1.T * m2
print(m5)

[[166 188 210]
 [188 214 240]
 [210 240 270]]


In [14]:
sm = np.arange(0, 11, 2).reshape((2, 3))
print(sm)
print(sm.shape)

[[ 0  2  4]
 [ 6  8 10]]
(2, 3)


In [15]:
test = m1 + 4
print(test)

[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]
 [14 15 16]]


In [16]:
sm2 = np.arange(1, 13).reshape((3, 4))
print(sm2)
print(sm2.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [17]:
print(m1.shape)
print(m1.shape[0])
print(m1.shape[1])

(4, 3)
4
3


In [18]:
m1 = m1.reshape(m1.shape[0] * m1.shape[1])
print(mat1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [19]:
r1 = np.matrix(np.arange(1, 7)).reshape((2, 3))
r2 = np.matrix(np.arange(2, 8)).reshape((2, 3))

r3 = np.array([
    r1, r2
])

print(r3)
print(r3.shape)

[[[1 2 3]
  [4 5 6]]

 [[2 3 4]
  [5 6 7]]]
(2, 2, 3)
